version: '3.4'

services:
  captureserv:
    build:
      target: development
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      # workaround for node_modules hiding problem, see https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html#the-node_modules-volume-trick
      - captureserv_node_modules:/usr/src/app/node_modules     
    command: ["npx", "nodemon", "--inspect=0.0.0.0:9229", "app.js"]

volumes:
  captureserv_node_modules:

