openapi: 3.0.0
info:
  title: Capture Service
  description: >
    Get state of hypnospace (page names and their links to each other)
    at a certain date.
  version: "1.0"

paths:
  /captures:
    get:
      summary: List available captures
      responses:
        "200":
          description: Available capture dates
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
                - "1999-11-05"
                - "1999-11-26"
                - "1999-12-31"
                - "20XX-XX-XX"

  /captures/{date}:
    get:
      summary: Get sitemap at date
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Capture
          content:
            application/json:
              schema:
                type: object
                properties:
                  pages:
                    type: array
                    items:
                      type: object
                      properties:
                        path:
                          type: string
                        name:
                          type: string
                        zone:
                          type: string
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        sourcePath:
                          type: string
                        targetPath:
                          type: string
        "404":
          description: invalid date
