apiVersion: v1
kind: Service
metadata:
  name: hs-captureserv
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: hs-captureserv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-captureserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hs-captureserv
  template:
    metadata:
      labels:
        app: hs-captureserv
    spec:
      containers:
      - name: hs-captureserv
        image: YOUR_CONTAINER_IMAGE_HERE
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: PRODUCTION
        - name: CORS_ALLOWED_ORIGINS
          value: "https://hypnospacemap.ca,https://www.hypnospacemap.ca"
