version: '3.4'

services:
  db:
    ports:
      - 27017:27017
  pageserv:
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
