version: '3.4'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  db-seed:
    image: mongo-seed
    build: 
      context: .
      dockerfile: ./Dockerfile.seed
    depends_on: 
      - "db"
    environment:
      MONGO_HOST: db
  pageserv:
    image: pageserv
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      MONGO_HOST: mongodb://db/hypnospace
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
