version: '3.4'

services:
  db:
    build:
      context: ./db
    ports:
      - "27017:27017"
    
  pageserv:
    image: pageserv
    build:
      context: .
    environment:
      NODE_ENV: development
      MONGO_HOST: mongodb://db/hypnospace
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
