openapi: 3.0.0
info:
  title: Page Service
  description: >
    Get details about Hypnospace pages
  version: "1.0"

paths:
  /captures:
    get:
      summary: List available captures
      tags:
        - captures
      responses:
        "200":
          description: Capture dates
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example: ["1999-11-05", "1999-11-26", "1999-12-31", "20XX-XX-XX"]

  /captures/{date}/pages:
    get:
      summary: List page names
      tags:
        - pages
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
          example: "1999-11-05"
        - name: zone
          in: query
          required: false
          description: Exact zone match
          schema:
            type: string
          example: "Hypnospace Central"
        - name: tags
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: nameOrDescription
          description: Return pages where name and/or description and/or path contains this argument
          in: query
          required: false
          schema:
            type: string
        - name: citizenName
          description: Fuzzy search term for citizen name. Empty string to search for pages with no citizen name.
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Pages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Page"
  /captures/{date}/pages/{path}:
    get:
      summary: Get single page by hsp path
      tags:
        - pages
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
          example: "1999-11-05"
        - name: path
          in: path
          required: true
          schema:
            type: string
          examples:
            forwardSlashes:
              value: "01_hypnospace central\\globalnewsroom.hsp"
              summary: With forward slashes
              description: >
                The default path format is {zone_name}{forward slash}{page.hsp}.
                Forward slash is url-encoded as %5C and in json is escaped as "\\\\"
            pipe:
              value: "01_hypnospace central|globalnewsroom.hsp"
              summary: With pipe character
              description: >
                Since the forward slashes are hard to deal with because of 
                url-encoding, character escaping, etc. you can use a | instead.
      responses:
        "200":
          description: Page found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Page"
        "404":
          description: Page not found

components:
  schemas:
    Page:
      type: object
      properties:
        path:
          type: string
        zone:
          type: string
        date:
          type: string
        name:
          type: string
          description: Page name
        tags:
          type: array
          items:
            type: string
        description:
          type: string
        citizenName:
          type: string
        linkedByAd:
          type: boolean
        linkedByMail:
          type: boolean
