version: '3.4'

services:
  page-serv:
    build:
      target: development
    environment:
      NODE_ENV: development
    ports:
      - 9230:9229
    volumes:
      - ./page-serv:/usr/src/app
      # workaround for node_modules hiding problem, see https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html#the-node_modules-volume-trick
      - page-serv_node_modules:/usr/src/app/node_modules     
    command: ["npx", "nodemon", "--inspect=0.0.0.0:9229", "app.js"]
    
  capture-serv:
    build:
      target: development
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    volumes:
      - ./capture-serv:/usr/src/app
      # workaround for node_modules hiding problem, see https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html#the-node_modules-volume-trick
      - capture-serv_node_modules:/usr/src/app/node_modules     
    command: ["npx", "nodemon", "--inspect=0.0.0.0:9229", "app.js"]

volumes:
  capture-serv_node_modules:
  page-serv_node_modules:

