version: '3.4'

services:
  page-serv:
    image: ${REGISTRY:-hs}/hs-page-serv:${TAG:-latest}
    build:
      context: page-serv
      target: production
    environment:
      NODE_ENV: production
      CORS_ALLOWED_ORIGINS: ${WEBAPP_EXTERNAL_DNS}
    ports:
      - 3000:3000

  capture-serv:
    image: ${REGISTRY:-hs}/hs-capture-serv:${TAG:-latest}
    build:
      context: capture-serv
      target: production
    environment:
      NODE_ENV: production
      CORS_ALLOWED_ORIGINS: ${WEBAPP_EXTERNAL_DNS}
    ports:
      - 3001:3000

  web:
    image: ${REGISTRY:-hs}/hs-web:${TAG:-latest}
    profiles:
    - frontend
    build:
      context: web 
      args:
        - DOT_ENV=${WEBAPP_DOT_ENV_PATH}
    depends_on:
      - page-serv
      - capture-serv 
    ports:
      - 5000:3000
