name: capture-serv test

on:
  push:
    branches: [ main ]
    paths:
      - 'src/capture-serv/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'src/capture-serv/**'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: docker-compose -f ./src/docker-compose.yml -f ./src/docker-compose.dev.yml build capture-serv
    
    - name: Lint
      run: docker-compose -f ./src/docker-compose.yml -f ./src/docker-compose.dev.yml run capture-serv npx eslint
      
    - name: Check code style
      run: docker-compose -f ./src/docker-compose.yml -f ./src/docker-compose.dev.yml run capture-serv npx prettier --check .
      
    - name: Run tests
      run: docker-compose -f ./src/docker-compose.yml -f ./src/docker-compose.dev.yml run capture-serv npm test
