name: Capture Service CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get timestamp for tag name
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV && echo $TAG
    - name: Build the Docker image
      run: docker build ./src/capture-serv --file ./src/capture-serv/Dockerfile.test --tag captureserv_test:$TAG
    - name: Run tests
      run: docker run captureserv_test:$TAG
