name: capture-serv test

on:
  push:
    branches: [ main ]
    paths:
      - 'src/capture-serv/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'src/capture-serv/**'

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run docker-compose
      run: docker-compose -f ./src/docker-compose.yml -f ./src/docker-compose.dev.yml run captureserv npm test
