name: Capture Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./src/capture-serv --file ./src/capture-serv/Dockerfile.test --tag captureserv_test:$(date +%s)
    - name: Run tests
      run: docker run captureserv_test:$(date +%s)
