# based on https://github.com/do-community/example-doctl-action/blob/master/.github/workflows/workflow.yaml
name: page-serv-build

on:
  push:
    branches:
      - main
    paths:
      - 'src/page-serv/**'
      - '.github/workflows/page-serv-build.yml'

jobs:

  build:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.digitalocean.com/gbarkway
      TAG: ${{ github.sha }}
      WEBAPP_EXTERNAL_DNS: "https://hypnospacemap.ca,https://www.hypnospacemap.ca"
      
    steps:

    - name: Checkout master
      uses: actions/checkout@master

    - name: Build container image
      run: docker-compose build pageserv
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: docker-compose push pageserv
