name: page-serv test

on:
  push:
    branches: [ main ]
    paths:
      - 'src/page-serv/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'src/page-serv/**'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: docker-compose -f ./src/docker-compose.yml -f ./src/docker-compose.dev.yml build pageserv pageserv-db
    
    - name: Lint
      run: docker-compose -f ./src/docker-compose.yml -f ./src/docker-compose.dev.yml run pageserv npx eslint
      
    - name: Check code style
      run: docker-compose -f ./src/docker-compose.yml -f ./src/docker-compose.dev.yml run pageserv npx prettier --check .
      
    - name: Run tests
      run: docker-compose -f ./src/docker-compose.yml -f ./src/docker-compose.dev.yml run pageserv npm test
